### ISSUE TITLE
[BUG] ImportError after #995

### ISSUE THREAD

**Issue by HuangJiameng** [deepmodeling/dpgen#1000]
After #995 is merged , `from dpgen import __date__` will raise error when executed. When using `dpgen -h` or any command, the following error message occurs.
```
(test) [root@bohrium /data/test_dpgen_devel/dpgen]$ dpgen -h
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/dpgen", line 5, in <module>
    from dpgen.main import main
  File "/usr/local/lib/python3.8/dist-packages/dpgen/main.py", line 19, in <module>
    from dpgen import info, __version__, __date__
ImportError: cannot import name '__date__' from 'dpgen' (/usr/local/lib/python3.8/dist-packages/dpgen/__init__.py)
``` 

**Steps to Reproduce**

clone the repo, then use
```
git checkout devel
pip install .
dpgen -h
```

**Comment by njzjz** [comment]
In #1001 I also add a test. Surprised to see there are no tests for `dpgen -h`.
