### ISSUE TITLE
[BUG] CP2K module cannot use in python 3.10

### ISSUE THREAD

**Issue by likefallwind** [deepmodeling/dpgen#1019]
**Summary**

CP2K module cannot use in python 3.10.

**DPGEN Version and Platform**

Bohrium Platform
DP-GEN version: 0.10.6

**Expected Behavior**

Just run CH4 example

**Actual Behavior**

Traceback (most recent call last):
  File "/opt/miniconda/envs/deepmd/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/generator/run.py", line 3642, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/generator/run.py", line 3625, in run_iter
    make_fp (ii, jdata, mdata)
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/generator/run.py", line 2827, in make_fp
    make_fp_cp2k(iter_index, jdata)
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/generator/run.py", line 2686, in make_fp_cp2k
    cp2k_input = make_cp2k_input(sys_data, fp_params)
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/generator/lib/cp2k.py", line 159, in make_cp2k_input
    update_dict(default_config, user_config)
  File "/opt/miniconda/envs/deepmd/lib/python3.10/site-packages/dpgen/generator/lib/cp2k.py", line 69, in update_dict
    if (k in old_d and isinstance(old_d[k], dict) and isinstance(update_d[k], collections.Mapping)):
AttributeError: module 'collections' has no attribute 'Mapping'

**Steps to Reproduce**

Use python 3.10 to run dpgen.

It is because module 'collections' has no attribute 'Mapping' in python 3.10, while it is use in dpgen/generator/lib/cp2k.py

**Comment by njzjz** [comment]
It should be changed to `collections.abc.Mapping`.
