### ISSUE TITLE
Dpgen cannot be installed

### ISSUE THREAD

**Issue by SimonkingCat** [deepmodeling/dpgen#1026]
(deepmd) dpgen
/root/anaconda3/envs/deepmd/lib/python3.10/site-packages/gromacs/__init__.py:286: GromacsImportWarning: Some Gromacs commands were NOT found; maybe source GMXRC first? The following are missing:
['release']

  warnings.warn("Some Gromacs commands were NOT found; "
Traceback (most recent call last):
  File "/root/.local/bin/dpgen", line 5, in <module>
    from dpgen.main import main
  File "/root/.local/lib/python3.10/site-packages/dpgen/main.py", line 15, in <module>
    from dpgen.auto_test.run import gen_test
  File "/root/.local/lib/python3.10/site-packages/dpgen/auto_test/run.py", line 9, in <module>
    from dpgen.auto_test.common_prop import make_property, run_property, post_property
  File "/root/.local/lib/python3.10/site-packages/dpgen/auto_test/common_prop.py", line 11, in <module>
    from dpgen.auto_test.Interstitial import Interstitial
  File "/root/.local/lib/python3.10/site-packages/dpgen/auto_test/Interstitial.py", line 7, in <module>
    from pymatgen.analysis.defects.generators import InterstitialGenerator
ModuleNotFoundError: No module named 'pymatgen.analysis.defects'

**Comment by SimonkingCat** [comment]
NOTE: Some configuration directories are not set up yet: 
	/root/.gromacswrapper
	/root/.gromacswrapper/qscripts
	/root/.gromacswrapper/templates
NOTE: You can create the configuration file and directories with:
	>>> import gromacs
	>>> gromacs.config.setup()
/root/anaconda3/envs/deepmd/lib/python3.10/site-packages/gromacs/__init__.py:286: GromacsImportWarning: Some Gromacs commands were NOT found; maybe source GMXRC first? The following are missing:
['release']

  warnings.warn("Some Gromacs commands were NOT found; "
Traceback (most recent call last):
  File "/root/.local/bin/dpgen", line 5, in <module>
    from dpgen.main import main
  File "/root/.local/lib/python3.10/site-packages/dpgen/main.py", line 15, in <module>
    from dpgen.auto_test.run import gen_test
  File "/root/.local/lib/python3.10/site-packages/dpgen/auto_test/run.py", line 9, in <module>
    from dpgen.auto_test.common_prop import make_property, run_property, post_property
  File "/root/.local/lib/python3.10/site-packages/dpgen/auto_test/common_prop.py", line 11, in <module>
    from dpgen.auto_test.Interstitial import Interstitial
  File "/root/.local/lib/python3.10/site-packages/dpgen/auto_test/Interstitial.py", line 7, in <module>
    from pymatgen.analysis.defects.generators import InterstitialGenerator
ModuleNotFoundError: No module named 'pymatgen.analysis.defects'

**Comment by wanghan-iapcm** [comment]
you may have to install the latest dpgen on devel branch or downgrade pymatgen to e.g. 2019.1.13, 2019.7.30
