### ISSUE TITLE
dpgen v0.11.0 incompatible with pwscf

### ISSUE THREAD

**Issue by pee8379** [deepmodeling/dpgen#1067]
With new dpgen v0.11.0,
(installed by command 
pip install dpgen
)
make error when using fp_style pwscf (quantum espresso) following : 

\\\\\\\\
Description
'------------
Traceback (most recent call last):
  File "/home/jjh/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/jjh/.local/lib/python3.10/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/home/jjh/.local/lib/python3.10/site-packages/dpgen/generator/run.py", line 3926, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/jjh/.local/lib/python3.10/site-packages/dpgen/generator/run.py", line 3739, in run_iter
    jdata = normalize(jdata_arginfo, jdata, strict_check=False)
  File "/home/jjh/.local/lib/python3.10/site-packages/dpgen/util.py", line 84, in normalize
    arginfo.check_value(data, strict=strict_check)
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 351, in check_value
    self.traverse_value(value, 
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 290, in traverse_value
    self._traverse_sub(value,
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 308, in _traverse_sub
    for subarg in self.flatten_sub(value, path).values():
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 255, in flatten_sub
    sub_dicts.extend(vrnt.flatten_sub(value, path) 
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 255, in <genexpr>
    sub_dicts.extend(vrnt.flatten_sub(value, path) 
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 667, in flatten_sub
    choice = self.get_choice(argdict, path)
  File "/home/jjh/.local/lib/python3.10/site-packages/dargs/dargs.py", line 657, in get_choice
    raise ArgumentValueError(path,
dargs.dargs.ArgumentValueError: [at root location] get invalid choice `pwscf` for flag key `fp_style`.
\\\\\\\\

with previous version, v0.10.6, 
(installed by command
git clone https://github.com/deepmodeling/dpgen.git
cd dpgen
pip install --user .
)
works flawlessly with pwscf, using identical PARAM and MACHINE json files.

It looks like 
https://github.com/deepmodeling/dpgen/pull/952
cause this problem, but I could not dig further. 

Thanks.

**Comment by wanghan-iapcm** [comment]
@njzjz  could you please help fix? Thanks!

**Comment by njzjz** [comment]
Fixed in #1068.
