### ISSUE TITLE
02.fp: No such file or directory: 'conf.dump'

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpgen#1143]
The structure is saved as 20 `traj_freq` in 01.model_devi, however, the 02.fp step includes structures in 10 `traj_freq`.

**param.json**:
        {   "sys_idx": [1],`"traj_freq": 20`,"_idx": "12",
           "template":{ "lmp": "./input.lammps", "plm": "./input.plumed" },
            "rev_mat":{ "lmp": {"V_NSTEPS": [30000], "V_TEMP": [300], "V_PRES": [1]},
                        "plm": {"V_TEMP":  [300], "V_AT": [4.0]}
                      }
        }

**erro**:
Traceback (most recent call last):
  File "/data/home/scv7215/deepmd-kit/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 3642, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 3625, in run_iter
    make_fp (ii, jdata, mdata)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 2827, in make_fp
    make_fp_cp2k(iter_index, jdata)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 2664, in make_fp_cp2k
    fp_tasks = _make_fp_vasp_configs(iter_index, jdata)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 2485, in _make_fp_vasp_configs
    fp_tasks = _make_fp_vasp_inner(modd_path, work_path,
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 2149, in _make_fp_vasp_inner
    dump_to_poscar('conf.dump', 'POSCAR', type_map, fmt = "lammps/dump")
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpgen/generator/run.py", line 194, in dump_to_poscar
    sys = dpdata.System(dump, fmt = fmt, type_map = type_map)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpdata/system.py", line 226, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step, **kwargs)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpdata/system.py", line 252, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpdata/system.py", line 255, in from_fmt_obj
    data = fmtobj.from_system(file_name, **kwargs)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpdata/plugins/lammps.py", line 44, in from_system
    lines = dpdata.lammps.dump.load_file(file_name, begin=begin, step=step)
  File "/data/home/scv7215/deepmd-kit/lib/python3.9/site-packages/dpdata/lammps/dump.py", line 132, in load_file
    with open(fname) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'conf.dump'

![image](https://user-images.githubusercontent.com/71744229/221216145-29b106e5-11bd-4eb7-b728-c40e24db85c9.png)

**Comment by AnguseZhang** [comment]
The error log seems incomplete, and I cannot locate the problem from you description. Could you make it more clear?

**Comment by caojiachun** [comment]
> The error log seems incomplete, and I cannot locate the problem from you description. Could you make it more clear?

Thank you, I think I already know what the problem is. THERMO_FREQ and dump Settings in input.lammps are inconsistent.
**input.lammps**:
variable        NSTEPS          equal 30000
variable        THERMO_FREQ     equal `10`
variable        DUMP_FREQ       equal 10
variable        TEMP            equal 300
variable        PRES            equal 1
variable        TAU_T           equal 0.100000
variable        TAU_P           equal 0.500000

units           metal
boundary        p p p
atom_style      atomic

neighbor        1.0 bin
box          	tilt large
read_data 	conf.lmp
change_box   	all triclinic
mass            1 15.999400
mass            2 1.007840
mass            3 12.010700
mass            4 32.066000

pair_style      deepmd ../graph.001.pb ../graph.000.pb  out_freq ${THERMO_FREQ} out_file model_devi.out 
pair_coeff       

fix            dpgen_plm all plumed plumedfile input.plumed outfile output.plumed

thermo_style    custom step temp pe ke etotal press vol lx ly lz xy xz yz
thermo          ${THERMO_FREQ}

dump            dpgen_dump all custom `20` traj/*.lammpstrj id type x y z
dump 		myDump all xyz 100 dump.0.xyz
dump_modify 	myDump element O H C S

velocity        all create ${TEMP} 26226

fix             1 all nvt temp ${TEMP} ${TEMP} ${TAU_T}

timestep        0.000200
run             ${NSTEPS}

**Comment by zjj12-zjj** [comment]
Hello, I encountered the same error as you.Judging by your comment, do you mean that it’s caused by the inconsistency between the THERMO_FREQ and dump settings in input.lammps?But when I checked my input.lammps file, these two parameters are set the same.Still, this error occurs.
