### ISSUE TITLE
AlN_ Tab still reports an error using an absolute path

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/dpgen#1165]
When running the run process, a new potential function model cannot be generated. An error is reported from 00.train/000/train.log as follows. AlN_ Tab still reports an error using an absolute path.
Report an error like this
=======================
Traceback (most recent call last):
  File "/opt/deepmd-kit-2.1.5/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 562, in main
    train_dp(**dict_args)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 107, in train
    _do_work(jdata, run_opt, is_compress)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 131, in _do_work
    model = DPTrainer(jdata, run_opt=run_opt, is_compress = is_compress)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/train/trainer.py", line 58, in __init__
    self._init_param(jdata)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/train/trainer.py", line 150, in _init_param
    self.model = EnerModel(
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/model/ener.py", line 75, in __init__
    self.srtab = PairTab(self.srtab_name)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/utils/pair_tab.py", line 27, in __init__
    self.reinit(filename)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/utils/pair_tab.py", line 45, in reinit
    self.vdata = np.loadtxt(filename)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: AlN_Tab not found.

**Comment by Chengqian-Zhang** [comment]
Can you give your param.json file and your dpgen version?

**Comment by XuFanffei** [comment]
gei it! I'll ask the teacher for these information



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chenqqian ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deepmodeling/dpgen] AlN_ Tab still reports an error using an absolute path (Issue #1165)





 
Can you give your param.json file and your dpgen version?

**Comment by Chengqian-Zhang** [comment]
You need to update dpgen to version 0.11.1 and add parameter "srtab_file_path".

**Comment by Chengqian-Zhang** [comment]
![image](https://user-images.githubusercontent.com/100290172/227451123-c4d07716-cfd2-4169-b5fa-7f195e4bd65f.png)
