### ISSUE TITLE
[BUG] cannot find upload file due to the conflict between pr#1127 and dpdispatcher

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/dpgen#1192]
**Summary**

If the number of elements of the structure in sys_configs is less than type_map ( for example, exploring the single component A in the alloy ABC ), it will report pp file of B and C cannot be uploaded. It seems that this pr #1127 makes dpgen only copy the pp and orb of the elements required by the structure in sys_configs, but the dpdispatcher is uploaded following all the elements in param.json.

**DPGEN Version and software of FP**

The version of DPGEN is 0.11.1 which is combined with ABACUS.

**Expected Behavior**

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/dpgen/bin/dpgen", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpgen/main.py", line 233, in main
    args.func(args)
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpgen/generator/run.py", line 5109, in gen_run
    run_iter(args.PARAM, args.MACHINE)
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpgen/generator/run.py", line 4461, in run_iter
    run_fp(ii, jdata, mdata)
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpgen/generator/run.py", line 3765, in run_fp
    run_fp_inner(
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpgen/generator/run.py", line 3702, in run_fp_inner
    submission.run_submission()
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpdispatcher/submission.py", line 219, in run_submission
    self.upload_jobs()
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpdispatcher/submission.py", line 421, in upload_jobs
    self.machine.context.upload(self)
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpdispatcher/ssh_context.py", line 570, in upload
    self._walk_directory(
  File "/home/user/anaconda3/envs/dpgen/lib/python3.11/site-packages/dpdispatcher/ssh_context.py", line 543, in _walk_directory
    raise RuntimeError(f"cannot find upload file {work_path} {jj}")
RuntimeError: cannot find upload file /home/user/colombo-ABACUS/run/iter.000001/02.fp/task.000.000000 Zn_ONCV_PBE-1.0.upf
```

**Steps to Reproduce**

This bug is easy to reproduce by the [example](https://gitee.com/deepmodeling/colombo-ABACUS/tree/master/ABACUS-DeePKS-DPGEN/run) with little modifications for adding an additional element such as Zn.

**Comment by pxlxingliang** [comment]
Hi @scott-5, this is really strange. PR #1127 is originally used to support the scenes you mentioned. In my server, I cannot reproduce this bug, can you provide me with the input files?

**Comment by pxlxingliang** [comment]
@scott-5 You are right, I have identified the problem codes. I will fix it latter.

**Comment by scott-5** [comment]
Thank you. Roughly tested with the commit code, the problem is solved. Expecting codes to be merged !
