### ISSUE TITLE
Problem with  dpgen run "AttributeError: 'str' object has no attribute 'from_str'"

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dpgen#1284]
### Discussed in https://github.com/deepmodeling/dpgen/discussions/1282

<div type='discussions-op-text'>

<sup>Originally posted by **Nancy877** July 20, 2023</sup>
Hello teacher,
When I use dpgen run, I meet the following errors:
INFO:dpgen:-------------------------iter.000000 task 05--------------------------
INFO:dpgen:-------------------------iter.000000 task 06--------------------------
INFO:dpgen:system 000 candidate :     56 in     93  60.22 %
INFO:dpgen:system 000 failed    :     35 in     93  37.63 %
INFO:dpgen:system 000 accurate  :      2 in     93   2.15 %
INFO:dpgen:system 000 accurate_ratio:   0.0215    thresholds: 1.0000 and 1.0000   eff. task min and max   -1    5   number of fp tasks:      5
Traceback (most recent call last):
  File "/opt/software/deepmd-kit/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen/main.py", line 233, in main
    args.func(args)
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen/generator/run.py", line 5109, in gen_run
    run_iter(args.PARAM, args.MACHINE)
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen/generator/run.py", line 4458, in run_iter
    make_fp(ii, jdata, mdata)
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen/generator/run.py", line 3516, in make_fp
    make_fp_vasp(iter_index, jdata)
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen/generator/run.py", line 3157, in make_fp_vasp
    make_fp_vasp_kp(iter_index, jdata)
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen/generator/run.py", line 2933, in make_fp_vasp_kp
    standard_incar = incar_upper(Incar.from_string(incar))
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/numpy/lib/utils.py", line 97, in newfunc
    return func(*args, **kwds)
  File "/opt/software/deepmd-kit/lib/python3.10/site-packages/pymatgen/io/vasp/inputs.py", line 766, in from_string
    return cls.from_str(*args, **kwargs)
AttributeError: 'str' object has no attribute 'from_str'

The installed software versions are as follows:
DeePMD-kit v2.2.2
dpgen Version: 0.11.1
Path:    /opt/software/deepmd-kit/lib/python3.10/site-packages/dpgen
Dependency
------------
     numpy     1.22.3   /opt/software/deepmd-kit/lib/python3.10/site-packages/numpy
    dpdata     0.2.15   /opt/software/deepmd-kit/lib/python3.10/site-packages/dpdata
  pymatgen            unknown version or path
     monty  2022.1.19   /opt/software/deepmd-kit/lib/python3.10/site-packages/monty
       ase     3.22.1   /opt/software/deepmd-kit/lib/python3.10/site-packages/ase
  paramiko      3.2.0   /opt/software/deepmd-kit/lib/python3.10/site-packages/paramiko
 custodian   2023.6.5   /opt/software/deepmd-kit/lib/python3.10/site-packages/custodian
DeePMD-kit v2.2.2

I doubt  whether this caused by a mismatch in my Python version.</div>

**Comment by njzjz** [comment]
This should be fixed by an upstream PR: https://github.com/materialsproject/pymatgen/pull/3177
