### ISSUE TITLE
_Replace With a Descriptive Title_

### ISSUE THREAD

**Issue by rebootablerye** [deepmodeling/dpgen#1339]
When I use DPGEN for run main process training, I want to add some data as initial data to the training. I add the data I want under init_data_sys in the input.json file. After using the DPGEN run command, the following error message appears This error: INFO:dpgen:=============================iter.000039==============================
INFO:dpgen:-------------------------iter.000039 task 00--------------------------
Traceback (most recent call last):
  File "/opt/mamba/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/dpgen/dpgen/main.py", line 233, in main
    args.func(args)
  File "/dpgen/dpgen/generator/run.py", line 5109, in gen_run
    run_iter(args.PARAM, args.MACHINE)
  File "/dpgen/dpgen/generator/run.py", line 4437, in run_iter
    make_train(ii, jdata, mdata)
  File "/dpgen/dpgen/generator/run.py", line 365, in make_train
    init_batch_size.append(detect_batch_size(ss, single_sys))
  File "/dpgen/dpgen/generator/run.py", line 618, in detect_batch_size
    s = dpdata.LabeledSystem(system, fmt=format)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 265, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step, convergence_check=convergence_check, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 291, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 1078, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/plugins/deepmd.py", line 60, in from_labeled_system
    return dpdata.deepmd.comp.to_system_data(file_name, type_map=type_map, labels=True)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/deepmd/comp.py", line 50, in to_system_data
    data['cells'] = np.concatenate(all_cells, axis = 0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

**Comment by njzjz** [comment]
Could you provide the data that throws the error?
