### ISSUE TITLE
Inappropriate format of OUTCAR file from abinito md calculations

### ISSUE THREAD

**Issue by LeiLiu8102** [deepmodeling/dpgen#149]
Hi all, thanks for sharing the amazing module. Could you please have a look at my issue below?

I have a problem at the stage of **preparing initial data**, specifically, at the substeps of 3 (Run a shor AIMD in folder 02.md)  and 4 (Collect data in folder in 02.md). The substeps 1 and 2 went through well and no issue came out. After the abinitio md calculations are finished, there is an error saying that it could not parse the OUTCAR file of md calculations correctly, as shown in the error message at the end.

Then I checked the OUTCAR file in `02.md` directory, found that the their format is not appropriate. For example, there is a line which contains "VOLUME and BASIS-vectors are now:"  but is not followed by volume matrix and vector matrix. One example is attached.

It seems that the data in OUTCAR file is not printed properly in abinitio md calculation (with VASP). I didn't encounter such issue before when I did VASP calculations on my own. It would be great if you have any clue that helps. Thanks!

[000001.zip](https://github.com/deepmodeling/dpgen/files/3748100/000001.zip)

"""
Traceback (most recent call last):
  File "/home/lliu147/miniconda2/envs/dpgen/bin/dpgen", line 10, in <module>
    sys.exit(main())
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpgen/main.py", line 125, in main
    args.func(args)
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpgen/data/gen.py", line 779, in gen_init_bulk
    coll_vasp_md(jdata)
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpgen/data/gen.py", line 536, in coll_vasp_md
    _sys = dpdata.LabeledSystem(oo)
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpdata/system.py", line 645, in __init__
    self.from_vasp_outcar(file_name, begin = begin, step = step)
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpdata/system.py", line 743, in from_vasp_outcar
    = dpdata.vasp.outcar.get_frames(file_name, begin = begin, step = step)
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpdata/vasp/outcar.py", line 65, in get_frames
    coord, cell, energy, force, virial, is_converge = analyze_block(blk, ntot, nelm)
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpdata/vasp/outcar.py", line 113, in analyze_block
    for ss in tmp_l.replace('-',' -').split()[0:3]])
  File "/home/lliu147/miniconda2/envs/dpgen/lib/python3.7/site-packages/dpdata/vasp/outcar.py", line 113, in <listcomp>
    for ss in tmp_l.replace('-',' -').split()[0:3]])
ValueError: could not convert string to float: 'FORHAR:'
"""

**Comment by amcadmus** [comment]
dpgen uses dpdata to load the information from OUTCARs. I tried the following command to load the OUTCAR in the attachment 
python3 -c "import dpdata; sys = dpdata.LabeledSystem('OUTCAR')"
and got an error that was not exactly the same as yours 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wanghan/.local/lib/python3.6/site-packages/dpdata-0.1.10-py3.6.egg/dpdata/system.py", line 645, in __init__
    self.from_vasp_outcar(file_name, begin = begin, step = step)
  File "/home/wanghan/.local/lib/python3.6/site-packages/dpdata-0.1.10-py3.6.egg/dpdata/system.py", line 743, in from_vasp_outcar
    = dpdata.vasp.outcar.get_frames(file_name, begin = begin, step = step)
  File "/home/wanghan/.local/lib/python3.6/site-packages/dpdata-0.1.10-py3.6.egg/dpdata/vasp/outcar.py", line 65, in get_frames
    coord, cell, energy, force, virial, is_converge = analyze_block(blk, ntot, nelm)
  File "/home/wanghan/.local/lib/python3.6/site-packages/dpdata-0.1.10-py3.6.egg/dpdata/vasp/outcar.py", line 101, in analyze_block
    assert((force is not None) and len(coord) > 0 and len(cell) > 0)
AssertionError

My dpdata version is 0.1.10.

Your are right the OUTCAR is not written correctly, the length of the coordinate array is 0, and the program raised an assertionError.  I do not find any problem in your input files, so I suspect that this is due to an I/O failure of your system. Could you please check 
1, if you can reproduce the error when you rerun dpgen
2, if you have similar not-correctly-written output files on your system.

**Comment by LeiLiu8102** [comment]
Hi, very appreciate your help for my last issue. I have found out why the OUTCAR file was not written correctly. It is because that I opened the file before the writing was finished, which might prevent the system from writing the file correctly.

I have another problem while running the program. At the stage of auto test, I set the "task_type" to be "vasp", and "task" to be "elastic".  The POSCAR file specified in the "conf_dir" contains two elements: "Si" and "O". Then an error message came out saying that:
> RuntimeError: stable energy and volume only for one element, current you have ['Si', 'O'] from POSCAR
Could you please help explain why the "stable energy and volume" only works for one element? 
The model I get in the previous stage (run) is trained for "Si-O" system. How should I set the PARAM file to test this model?

Best,
Lei

**Comment by BaozCWJ** [comment]
> Hi, very appreciate your help for my last issue. I have found out why the OUTCAR file was not written correctly. It is because that I opened the file before the writing was finished, which might prevent the system from writing the file correctly.
> 
> I have another problem while running the program. At the stage of auto test, I set the "task_type" to be "vasp", and "task" to be "elastic". The POSCAR file specified in the "conf_dir" contains two elements: "Si" and "O". Then an error message came out saying that:
> 
> > RuntimeError: stable energy and volume only for one element, current you have ['Si', 'O'] from POSCAR
> > Could you please help explain why the "stable energy and volume" only works for one element?
> > The model I get in the previous stage (run) is trained for "Si-O" system. How should I set the PARAM file to test this model?
> 
> Best,
> Lei

You can set the "store_stable" to "False" while testing. It is a useless argument and we will remove it in the next update. Thx!
