### ISSUE TITLE
[BUG] UnboundLocalError: cannot access local variable 'stepbindex' where it is not associated with a value

### ISSUE THREAD

**Issue by PenguinW1105** [deepmodeling/dpgen#1490]
### Bug summary

When I used dpgen init_reaction to build my dataset in WSL2(Ubuntu 20.04), I met with the error  "Unbound Local Error: cannot access local variable 'stepbindex' where it is not associated with a value". At first, in order to learn how to solve this problem, I used the same file and runed it  on the Windows, but the problem did not appear. The specific message was shown in the part of  "Steps to Reproduce"

### DP-GEN Version

0.12.0

### Platform, Python Version, Remote Platform, etc

WSL2(Ubuntu 20.04), python 3.11.4 

### Input Files, Running Commands, Error Log, etc.

Input files has been uploaded [param.json] [machine.json]
[machine.json](https://github.com/deepmodeling/dpgen/files/14718966/machine.json)
[param.json](https://github.com/deepmodeling/dpgen/files/14718967/param.json)

Running Commands: dpgen init_reaction param.json machine.json

Error Log: 
Traceback (most recent call last):
  File "/home/penguinw/anaconda3/bin/datasetbuilder", line 8, in <module>
    sys.exit(_commandline())
             ^^^^^^^^^^^^^^
  File "/home/penguinw/anaconda3/lib/python3.11/site-packages/mddatasetbuilder/datasetbuilder.py", line 711, in _commandline
    DatasetBuilder(
  File "/home/penguinw/anaconda3/lib/python3.11/site-packages/mddatasetbuilder/datasetbuilder.py", line 109, in __init__
    self.crddetector = Detect.gettype("dump")(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/penguinw/anaconda3/lib/python3.11/site-packages/mddatasetbuilder/detect.py", line 23, in __init__
    self.steplinenum = self._readN()
                       ^^^^^^^^^^^^^
  File "/home/penguinw/anaconda3/lib/python3.11/site-packages/mddatasetbuilder/detect.py", line 168, in _readN
    steplinenum = stepbindex - stepaindex
                  ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'stepbindex' where it is not associated with a value

### Steps to Reproduce

Firstly, I used the command "dpgen init_reaction param.json machine.json" and then the error appeared.
Secondly, I used another simple file to run lammps and produce the lammpstrj and bond file. And then I used the files to run the command " datasetbuilder -d pyrolysis.lammpstrj -b pyrolysis.bonds.out -a C H N O S -np 4 -c 6 -s 5000 -n pyrolysis" on the Windows Platform by anaconda prompt, and it did not appear any error.
Thirdly, I used the file which was the same one used in  the second path to run the command "dpgen init_reaction param.json machine.json", but the error still appeared.

**Comment by njzjz** [comment]
Please check two things and may post here:

(1) the final command you ran, which should be in `*.sub.run` file in the remote root;
(2) the lammps dump file in the remote root is not broken.

**Comment by PenguinW1105** [comment]
> Please check two things and may post here:
> 
> (1) the final command you ran, which should be in `*.sub.run` file in the remote root; (2) the lammps dump file in the remote root is not broken.

I seem to know what generates this problem. The lammpstrj in the 01.build/task.000 seem to be broken, and the specific message of the sub.run file was here:
cd $REMOTE_ROOT
cd task.000
test $? -ne 0 && exit 1
if [ ! -f 9307c5b04012a935431bbe1f56d6e3dd6d103dc0_task_tag_finished ] ;then
   ( datasetbuilder -n dpgen_init -a C H O N S -d lammpstrj -c 6.0 -s 5000 -k "force m062x/6-31g** Geom=PrintInputOrient" --nprocjob 1 --nproc 1 ) 1>>build_log 2>>build_log 
  if test $? -eq 0; then touch 9307c5b04012a935431bbe1f56d6e3dd6d103dc0_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab1afb0fe00ed3fd28f23039df670e0ad1d79aa2_flag_if_job_task_fail;tail -v -c 1000 $REMOTE_ROOT/task.000/build_log > $REMOTE_ROOT/ab1afb0fe00ed3fd28f23039df670e0ad1d79aa2_last_err_file;fi
fi &
wait
