### ISSUE TITLE
dpgen: AssertionError: cannot find coords

### ISSUE THREAD

**Issue by zhbzhbzhbzhb** [deepmodeling/dpgen#1534]
### Summary

depgen encounters an error after completing the fp task when performing fp calculations with cp2k.

Traceback (most recent call last):
  File "/opt/mamba/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/generator/run.py", line 3926, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/generator/run.py", line 3812, in run_iter
    post_fp (ii, jdata)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/generator/run.py", line 3691, in post_fp
    post_fp_cp2k(iter_index, jdata)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/generator/run.py", line 3568, in post_fp_cp2k
    _sys = dpdata.LabeledSystem(oo, fmt = 'cp2k/output')
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 265, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step, convergence_check=convergence_check, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 291, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 1078, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/plugins/cp2k.py", line 27, in from_labeled_system
    = dpdata.cp2k.output.get_frames(file_name)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/cp2k/output.py", line 377, in get_frames
    assert(coord), "cannot find coords"
AssertionError: cannot find coords

### DP-GEN Version

0.11.0

### Details

The input file and log  of dpgen and cp2k input file are in the zip
[dpgen.zip](https://github.com/deepmodeling/dpgen/files/15157477/dpgen.zip)

**Comment by njzjz** [comment]
I see the input file, but could you provide the output file?

**Comment by zhbzhbzhbzhb** [comment]
Thanks for your time. After I changing the cp2k.inp "print level: medium", it works well.
