### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xwxwshi** [deepmodeling/dpgen#1595]
### Summary

Running aimd (vasp) in the init step of DP-GEN gives an error with the message IndexError: list index out of range.

### DP-GEN Version

dpgen:0.12.0

### Details

Traceback (most recent call last):
  File "/opt/mamba/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/main.py", line 255, in main
    args.func(args)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/data/gen.py", line 1581, in gen_init_bulk
    coll_vasp_md(jdata)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/data/gen.py", line 1107, in coll_vasp_md
    _sys = dpdata.LabeledSystem(oo, type_map=type_map)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 183, in __init__
    self.from_fmt(
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 220, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 1113, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/plugins/vasp.py", line 94, in from_labeled_system
    data = uniq_atom_names(data)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/utils.py", line 97, in uniq_atom_names
    data["atom_types"] = np.array([uidxmap[jj] for jj in tmp_type], dtype=int)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/utils.py", line 97, in <listcomp>
    data["atom_types"] = np.array([uidxmap[jj] for jj in tmp_type], dtype=int)
IndexError: list index out of range

**Comment by njzjz** [comment]
Duplicate of https://github.com/deepmodeling/dpdata/issues/359
