### ISSUE TITLE
An Error when running the iter.1

### ISSUE THREAD

**Issue by wxy20010110** [deepmodeling/dpgen#315]
INFO:dpgen:=============================iter.000001==============================
INFO:dpgen:-------------------------iter.000001 task 00--------------------------
INFO:dpgen:-------------------------iter.000001 task 01--------------------------
INFO:dpgen:-------------------------iter.000001 task 02--------------------------
INFO:dpgen:-------------------------iter.000001 task 03--------------------------
Traceback (most recent call last):
  File "/nfs-share/home/1800011848/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/main.py", line 182, in main
    args.func(args)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2309, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2278, in run_iter
    cont = make_model_devi (ii, jdata, mdata)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 687, in make_model_devi
    ss = sys_configs[idx]
IndexError: list index out of range

**Comment by amcadmus** [comment]
Please check the size of list sys_config provided by the parameter file
