### ISSUE TITLE
Hi. After the pip install of dpgen, I run the command and the problem shows up

### ISSUE THREAD

**Issue by chenyouheng** [deepmodeling/dpgen#327]
Traceback (most recent call last):
  File "/home/dengbin/miniconda3/bin/dpgen", line 5, in <module>
    from dpgen.main import main
  File "/home/dengbin/.local/lib/python3.8/site-packages/dpgen/main.py", line 9, in <module>
    from dpgen.generator.run import gen_run
  File "/home/dengbin/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 42, in <module>
    from dpgen.generator.lib.vasp import write_incar_dict
  File "/home/dengbin/.local/lib/python3.8/site-packages/dpgen/generator/lib/vasp.py", line 5, in <module>
    from pymatgen.io.vasp import Incar
  File "/home/dengbin/.local/lib/python3.8/site-packages/pymatgen/__init__.py", line 14, in <module>
    import ruamel.yaml as yaml

How to solve this problem?       
             

> Thank you!

**Comment by njzjz** [comment]
What’s the error? `ModuleNotFoundError`?

**Comment by chenyouheng** [comment]
> What’s the error? `ModuleNotFoundError`?

![Uploading 96292737...]()
Yes,this is the info

**Comment by njzjz** [comment]
You may use `pip install ruamel.yaml` to install it.

**Comment by njzjz** [comment]
This is likely to be a bug and we will investigate it.

**Comment by chenyouheng** [comment]
I changed the python version from 3.8 to 3.6 and the problem is solved

**Comment by hanyecn** [comment]
python 3.7, have the same problem
