### ISSUE TITLE
Issue of dpgen on PBS system

### ISSUE THREAD

**Issue by Manyi-Yang** [deepmodeling/dpgen#395]
**Summary**
I run DPGEN jobs (dpgen run) on localhost and want to do calculations (such as dp train, DFT calculate) on the remote HPC.  
DPGEN can distribute tasks to the remote HPC (batch: PBS). But finishing the calculation, it failed to collect the data from HPC.

**DPGEN Version and Platform**
Version: 0.9.1.dev0+g769ccf4.d20210504
ubuntu  20.4

**Details**
Description
------------
Traceback (most recent call last):
  File "/home/myang@iit.local/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2410, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2373, in run_iter
    run_train  (ii, jdata, mdata)
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 529, in run_train
    dispatcher.run_jobs(mdata['train_resources'],
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 91, in run_jobs
    while not self.all_finished(job_handler, mark_failure) :
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 210, in all_finished
    status = rjob['batch'].check_status()
  File "/home/myang@iit.local/.local/lib/python3.8/site-packages/dpgen/dispatcher/PBS.py", line 25, in check_status
    raise RuntimeError ("status command qstat fails to execute. erro info: %s return code %d"
RuntimeError: status command qstat fails to execute. erro info: qstat: 10169.franklin01 Job has finished, use -x or -H to obtain historical job information
 return code 35

**Comment by AnguseZhang** [comment]
Fixed by #396
