### ISSUE TITLE
Issue in DPGEN init step about "cvasp.py"

### ISSUE THREAD

**Issue by ZhanPengOu** [deepmodeling/dpgen#487]
Hi,developers,
something wrong has happened when i use the subcommand "init_bulk" in DPGEN.
Error messages are following

 nohup: 忽略输入
 /home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/gromacs/__init__.py:271: GromacsImportWarning: Some Gromacs commands were NOT found; maybe s    ource GMXRC first? The following are missing:
 ['release']

  warnings.warn("Some Gromacs commands were NOT found; "
/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/data/gen.py:588: UserWarning: the dpdispatcher will be updated to new version.And the     interface may be changed. Please check the documents for more details warnings.warn(f"the dpdispatcher will be updated to new version."
/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/ase/atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
warnings.warn('Use get_global_number_of_atoms() instead',
/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/data/gen.py:653: UserWarning: the dpdispatcher will be updated to new version.And the     interface may be changed. Please check the documents for more details
warnings.warn(f"the dpdispatcher will be updated to new version."
Traceback (most recent call last):
File "/home/zpou/anaconda3/envs/dpgen/bin/dpgen", line 8, in <module>
sys.exit(main())
File "/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/main.py", line 175, in main
args.func(args)
File "/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/data/gen.py", line 762, in gen_init_bulk
run_vasp_md(jdata, mdata)
File "/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/data/gen.py", line 656, in run_vasp_md
dispatcher.run_jobs(fp_resources,
File "/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/dispatcher/Dispatcher.py", line 84, in run_jobs
job_handler = self.submit_jobs(resources,
File "/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/dispatcher/Dispatcher.py", line 144, in submit_jobs
rjob['context'].upload('.',
File "/home/zpou/anaconda3/envs/dpgen/lib/python3.9/site-packages/dpgen/dispatcher/LocalContext.py", line 80, in upload
raise RuntimeError('cannot find upload file ' + os.path.join(local_job, jj))
RuntimeError: cannot find upload file /home/zpou/metaD/Si/cluster_dpgen/size/init_test/POSCAR.01x01x01/02.md/./cvasp.py

it is so strange that the relax step of init_bulk, the folder "00.place_ele" has the "cvasp.py" and run without error.
However, after coping the "cvasp.py" to "02.md" folder by myself ,  there no more error messages, so i wondering if something wrong in my param.json or a bug.

thanks for your help.

DPGEN version: 0.10.0
[Si_init.zip](https://github.com/deepmodeling/dpgen/files/6936837/Si_init.zip)

**Comment by AnguseZhang** [comment]
Thanks for reporting the problem.
I've fixed this problem in #482 

Btw, I have a question. Do you have the need for `cvasp`? Thanks!

Yuzhi
