### ISSUE TITLE
[BUG] Some of autotest initersitial jobs fail to create element.out

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/dpgen#500]
**Summary**

Some of the autotest interstitial jobs raise this Error when performing `dpgen autotest make interstitial.json`, some don't.
```python
Traceback (most recent call last):
  File "/opt/anaconda3/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/opt/anaconda3/lib/python3.7/site-packages/dpgen/auto_test/run.py", line 57, in gen_test
    run_task(args.TASK, args.PARAM, args.MACHINE)
  File "/opt/anaconda3/lib/python3.7/site-packages/dpgen/auto_test/run.py", line 28, in run_task
    make_property(confs, inter_parameter, property_list)
  File "/opt/anaconda3/lib/python3.7/site-packages/dpgen/auto_test/common_prop.py", line 95, in make_property
    prop.post_process(task_list)  # generate same KPOINTS file for elastic when doing VASP
  File "/opt/anaconda3/lib/python3.7/site-packages/dpgen/auto_test/Interstitial.py", line 179, in post_process
    fin1 = open(os.path.join(task_list[0], '..', 'element.out'), 'r')
IndexError: list index out of range
```
 The input.json files are the same:
```json
{
    "structures":       ["confs/Si/mp-1196961"],
    "interaction": {
        "type":          "vasp",
        "incar":         "../vasp_input/INCAR.rlx",
        "potcar_prefix": "../vasp_input/",
        "potcars":       {"Si": "POTCAR"}
    },  
    "properties": [
        {   
         "type":         "interstitial",
         "supercell":    [1, 1, 1], 
         "insert_ele":   ["Si"],
         "conf_filters": {"min_dist": 1.5},
         "cal_setting":  {"input_prop": "../vasp_input/INCAR"}
        }   
    ]   
}
```
**DPGEN Version and Platform**

DPGEN version: 0.10.0
platform: ALI ECS
**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by smismyname** [comment]
when  performing dpgen autotest make property.json in the autotest_deepmd，i got the same error.someoneelse can help me solve the problem?

**Comment by SimonkingCat** [comment]
Me too
