### ISSUE TITLE
[BUG] _autotest_make_interstitial_"AttributeError: element"_

### ISSUE THREAD

**Issue by Vibsteamer** [deepmodeling/dpgen#502]
**Summary**
Can't create interstitial structure for specific element (Sc)

**DPGEN Version and Platform**
```
DeepModeling
------------
Version: 0.8.1.dev273+g815c9ce.d20210816
Date:    Aug-16-2021
Path:    /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpgen

Dependency
------------
     numpy     1.20.2   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/numpy
    dpdata      0.2.0   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpdata
  pymatgen   2019.6.5   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/pymatgen
     monty      2.0.4   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/monty
       ase     3.17.0   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/ase
  paramiko      2.6.0   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/paramiko
 custodian  2019.2.10   /opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/custodian
```

**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**
```
Description
------------
------------------------------confs/bcc-------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dpgen/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpgen/auto_test/run.py", line 57, in gen_test
    run_task(args.TASK, args.PARAM, args.MACHINE)
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpgen/auto_test/run.py", line 28, in run_task
    make_property(confs, inter_parameter, property_list)
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpgen/auto_test/common_prop.py", line 80, in make_property
    task_list = prop.make_confs(path_to_work, path_to_equi, do_refine)
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/dpgen/auto_test/Interstitial.py", line 136, in make_confs
    vds = InterstitialGenerator(ss, ii)
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/pymatgen/analysis/defects/generators.py", line 160, in __init__
    interstitial_finder = StructureMotifInterstitial(self.structure, self.element)
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/pymatgen/analysis/defects/utils.py", line 350, in __init__
    elem = site.specie.element.symbol
  File "/opt/anaconda3/envs/dpgen/lib/python3.7/site-packages/pymatgen/core/periodic_table.py", line 1413, in __getattr__
    raise AttributeError(a)
AttributeError: element
```

**Steps to Reproduce**
```
dpgen autotest make PARAM
```
PARAM see below

**Further Information, Files, and Links**
PARAM
```
{
    "structures":       ["confs/bcc","confs/hcp","confs/fcc"],
    "interaction": {
        "type":          "vasp",
        "incar":         "./INCAR",
        "potcar_prefix": "./",
        "potcars":       {"Sc": "POTCAR_Sc"}
    },
    "properties": [

        {
         "type":         "interstitial",
         "supercell":    [2, 2, 2],
         "insert_ele":   ["Sc"],
         "conf_filters": {"min_dist": 1.5}
        }
    ]
}
```

Please touch-then-create-empty-files for those file needed by the file-exist check in "dpgen autotest make".

[confs.zip](https://github.com/deepmodeling/dpgen/files/7023272/confs.zip)

**Comment by HuangJiameng** [comment]
https://github.com/deepmodeling/dpgen/pull/696 I hope this may help you.

**Comment by Vibsteamer** [comment]
might be a element-type-dependent problem of pymatgen, has communicated with HuangJiameng, closed here.
