### ISSUE TITLE
`coord_norm` is not allowed in strict mode

### ISSUE THREAD

**Issue by zcb-code** [deepmodeling/dpgen#535]
I have installed the deepmdkit 2.0; dpgen 0.9.2. To repeat the CH4 example, I got the flowing error. Even if I cp input_v2_compat.json input.json, it still did not help. 

2021-08-31 12:00:04.457066: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
WARNING:deepmd.train.run_options:Switch to serial execution due to lack of horovod module.
Traceback (most recent call last):
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 87, in train
    jdata = normalize(jdata)
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/deepmd/utils/argcheck.py", line 660, in normalize
    base.check_value(data, strict=True)
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 278, in check_value
    self.traverse_value(argdict,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 260, in _traverse_sub
    subarg.traverse(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 228, in traverse
    self.traverse_value(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 260, in _traverse_sub
    subarg.traverse(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 228, in traverse
    self.traverse_value(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 256, in _traverse_sub
    sub_hook(self, value, path)
  File "/home/elgao/scratch/miniconda3_bob/envs/deepmd/lib/python3.9/site-packages/dargs/dargs.py", line 307, in _check_strict
    raise ArgumentKeyError(path,
dargs.dargs.ArgumentKeyError: [at location `model/fitting_net`] undefined key `coord_norm` is not allowed in strict mode

**Comment by zcb-code** [comment]
It worked after deleting the following three lines: 
 "coord_norm":       true,
 "save_freq":          1000,
 "load_ckpt":         "model.ckpt",

**Comment by zhoujingyu13687306871** [comment]
> 

hello , did you say ,deleted the following three lines: 
"coord_norm": true,
"save_freq": 1000,
"load_ckpt": "model.ckpt",
of param.json ?

**Comment by zhoujingyu13687306871** [comment]
I have installed the deepmdkit 2.0.3; dpgen 0.10.5. To repeat the CH4 example
Even though I removed the 3 parameters mentioned above , it still reported the same error : dargs.dargs.ArgumentKeyError: [at location model/fitting_net] undefined key coord_norm is not allowed in strict mode

,

**Comment by 343333333** [comment]
> I have installed the deepmdkit 2.0.3; dpgen 0.10.5. To repeat the CH4 example Even though I removed the 3 parameters mentioned above , it still reported the same error : dargs.dargs.ArgumentKeyError: [at location model/fitting_net] undefined key coord_norm is not allowed in strict mode
> 
> ,

Hello, 
the reason why it collapsed is the script is for dp 1.x.x now you use 2.0.3. Try to delete the keywords——’coord_norm‘，’save_freq‘，’load_ckpt‘，’type_fitting_net‘.
Same version dpmd and dpgen , same error . I delete these keywords now it work.
