### ISSUE TITLE
[BUG] UT on post_cp2k failed.

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/dpgen#597]
**Summary**

UT on post_cp2k failed.

**DPGEN Version and Platform**

on devel branch

**Expected Behavior**

UT passes

**Actual Behavior**

UT failed with error log:
```
test_atom_names (tests.generator.test_post_fp.TestPostCP2K) ... /home/wanghan/study/deep.md/venvs/py3.6-tf1.8/lib/python3.6/site-packages/dpdata/plugins/cp2k.py:27: ResourceWarning: unclosed file <_io.TextIOWrapper name='iter.000000/02.fp/task.000.000000/output' mode='r' encoding='UTF-8'>
  = dpdata.cp2k.output.get_frames(file_name)
ERROR

======================================================================
ERROR: test_atom_names (tests.generator.test_post_fp.TestPostCP2K)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wanghan/study/deep.md/dpgen/tests/generator/test_post_fp.py", line 242, in setUp
    post_fp(0, jdata)
  File "/home/wanghan/study/deep.md/dpgen/dpgen/generator/run.py", line 2837, in post_fp
    post_fp_cp2k(iter_index, jdata)
  File "/home/wanghan/study/deep.md/dpgen/dpgen/generator/run.py", line 2762, in post_fp_cp2k
    all_sys.to_deepmd_raw(sys_data_path)
  File "/home/wanghan/study/deep.md/venvs/py3.6-tf1.8/lib/python3.6/site-packages/dpdata/system.py", line 1263, in to_format
    return self.to_fmt_obj(ff(), *args, **kwargs)
  File "/home/wanghan/study/deep.md/venvs/py3.6-tf1.8/lib/python3.6/site-packages/dpdata/system.py", line 903, in to_fmt_obj
    return fmtobj.to_labeled_system(self.data, *args, **kwargs)
  File "/home/wanghan/study/deep.md/venvs/py3.6-tf1.8/lib/python3.6/site-packages/dpdata/format.py", line 77, in to_labeled_system
    return self.to_system(data, *args, **kwargs)
  File "/home/wanghan/study/deep.md/venvs/py3.6-tf1.8/lib/python3.6/site-packages/dpdata/plugins/deepmd.py", line 18, in to_system
    dpdata.deepmd.raw.dump(file_name, data)
  File "/home/wanghan/study/deep.md/venvs/py3.6-tf1.8/lib/python3.6/site-packages/dpdata/deepmd/raw.py", line 64, in dump
    nframes = data['cells'].shape[0]
AttributeError: 'list' object has no attribute 'shape'

----------------------------------------------------------------------
Ran 1 test in 0.007s

FAILED (errors=1)

```

**Steps to Reproduce**

at `dpgen` source roor, run 
```bash
python -m unittest tests.generator.test_post_fp.TestPostCP2K  -f -v
```

**Comment by wanghan-iapcm** [comment]
Fixed by #598
