### ISSUE TITLE
Run dpgen error about pymatgen

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/dpgen#612]
I have installed dpgen by command "pip install --user .", and the install is successful.
But after i execute the command "dpgen -h", i receive an error message:

Traceback (most recent call last):
  File "/home/pxl/.local/bin/dpgen", line 5, in <module>
    from dpgen.main import main
  File "/home/pxl/.local/lib/python3.9/site-packages/dpgen/main.py", line 9, in <module>
    from dpgen.generator.run import gen_run
  File "/home/pxl/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 44, in <module>
    from dpgen.generator.lib.vasp import write_incar_dict
  File "/home/pxl/.local/lib/python3.9/site-packages/dpgen/generator/lib/vasp.py", line 5, in <module>
    from pymatgen.io.vasp import Incar
  File "/home/pxl/miniconda3/lib/python3.9/site-packages/pymatgen/io/vasp/__init__.py", line 13, in <module>
    from .inputs import Incar, Kpoints, Poscar, Potcar, PotcarSingle, VaspInput  # noqa
  File "/home/pxl/miniconda3/lib/python3.9/site-packages/pymatgen/io/vasp/inputs.py", line 33, in <module>
    from pymatgen.core import SETTINGS
  File "/home/pxl/miniconda3/lib/python3.9/site-packages/pymatgen/core/__init__.py", line 21, in <module>
    from .lattice import Lattice  # noqa
  File "/home/pxl/miniconda3/lib/python3.9/site-packages/pymatgen/core/lattice.py", line 23, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/pxl/miniconda3/lib/python3.9/site-packages/pymatgen/util/coord.py", line 17, in <module>
    from . import coord_cython as cuc
ImportError: /home/pxl/miniconda3/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strlen

i try to install an older pymatgen version 2022.0.5 (after uninstall the installed version) before installing dpgen, but it doesn't work.

**Comment by AnguseZhang** [comment]
<img width="711" alt="Screen Shot 2021-12-11 at 1 04 11 AM" src="https://user-images.githubusercontent.com/38939321/145612996-081ae66e-7e10-4970-a59d-63866b6264a6.png">

**Comment by AnguseZhang** [comment]
You need make sure that `from pymatgen.io.vasp import Incar` can be executed.  And this is not related to `DP-GEN`, but `pymatgen`. Just find what goes wrong on your `pymatgen`

**Comment by njzjz** [comment]
Please report to [pymatgen](https://github.com/materialsproject/pymatgen) instead.
