### ISSUE TITLE
FileExistsError and FileNotFoundError in dpgen init_bulk

### ISSUE THREAD

**Issue by PKUfjh** [deepmodeling/dpgen#636]
when I run dpgen init_bulk ch4.json, I get the following error

Traceback (most recent call last):
  File "/gpfs/share/home/2001110077/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/data/gen.py", line 770, in gen_init_bulk
    create_path(out_dir)
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/data/gen.py", line 53, in create_path
    os.makedirs (path)
  File "/gpfs/share/home/2001110077/software/miniconda3/envs/deepmd/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'CH4.POSCAR.01x01x01/'

Traceback (most recent call last):
  File "/gpfs/share/home/2001110077/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/data/gen.py", line 783, in gen_init_bulk
    make_vasp_relax(jdata, {"fp_resources":{}})
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/data/gen.py", line 311, in make_vasp_relax
    os.remove(os.path.join(work_dir, 'INCAR' ))
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/share/home/2001110077/software/dpgen/examples/init/ch4/CH4.POSCAR.01x01x01/00.place_ele/INCAR'

Traceback (most recent call last):
  File "/gpfs/share/home/2001110077/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/data/gen.py", line 786, in gen_init_bulk
    make_scale(jdata)
  File "/gpfs/share/home/2001110077/.local/lib/python3.7/site-packages/dpgen/data/gen.py", line 375, in make_scale
    raise RuntimeError("not file %s, vasp relaxation should be run before scale poscar")
RuntimeError: not file %s, vasp relaxation should be run before scale poscar

But in fact I have INCAR in this path, I do not know what the problem is.

DPGEN version: 0.10.3
python version: 3.7.11
Platform: 北京大学超算：生科一号

params.json:
{
    "stages":           [1,2,3,4],
    "cell_type":	"diamond",
    "super_cell":	[1, 1, 1],
    "elements":		["H","C"],
    "from_poscar":	true,
    "from_poscar_path":	"./CH4.POSCAR",
    "potcars":		["./POTCAR_H", "./POTCAR_C"],
    "relax_incar": 	"./INCAR_methane.rlx",
    "md_incar" : 	"./INCAR_methane.md",
    "scale":		[1.00],
    "skip_relax":	false,
    "pert_numb":	30,
    "md_nstep" : 	10,
    "pert_box":		0.03,
    "pert_atom":	0.01,
    "deepgen_templ":	"../generator/template/",
    "coll_ndata":	5000,
    "_comment":		"that's all"
}

I submit the job by command "sbatch job.sh"
job.sh:
#!/bin/bash
#SBATCH -o job.%j.out
#SBATCH -p C032M0128G
#SBATCH --qos=high
#SBATCH -J dpgen
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4

module load intel/2017.1
module load vasp/5.4.4-intel-2017.1
mpirun -np 4 dpgen init_bulk ch4.json > init.log

**Details**

**Comment by AnguseZhang** [comment]
1. You do not need to run `mpirun` for `dpgen init_bulk `.  I suggest that run `dpgen init_bulk Ch4.json` and see the error log  again. That log would be helpful for locating the problem. 
2. To run all stages in `init_bulk`, `machine.json` should be correctly configured. You can see manual for reference.

**Comment by njzjz** [comment]
I'll close the issue. It looks like using MPI is the reason for the error, which is entirely wrong.

**Comment by HRHTer** [comment]
I met the same error today and I didn't use MPI  
#!/bin/sh
# -- ab2 --

#BSUB -J test
# -- specify queue –
#BSUB -q normal
# -- number of processors --
#BSUB -n 10
# --Specify the output and error file. %J is the job-id --
# -- -o and -e mean append, -oo and -eo mean overwrite --
#BSUB -oo test%J.out
#BSUB -eo test%J.err

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/data/home/hrht/deepmd-kit/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/data/home/hrht/deepmd-kit/etc/profile.d/conda.sh" ]; then
        . "/data/home/hrht/deepmd-kit/etc/profile.d/conda.sh"
    else
        export PATH="/data/home/hrht/deepmd-kit/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize << <


dpgen init_bulk param.json
