### ISSUE TITLE
dpgen autotest encounter an error "assert( len(data['atom_names'])==len(data['atom_numbs']) )"

### ISSUE THREAD

**Issue by xwchen2019** [deepmodeling/dpgen#680]
**Summary**

I used "dpgen autotest run param machine" to run the eos task, and it goes well. Then I use "dpgen autotest post param" to get the eos results, and encounter an error "assert( len(data['atom_names'])==len(data['atom_numbs']) )"
my param file is as below

{
	"structures":	["confs"],
	"interaction": {
		"type":		"vasp",
		"incar":	"relax_incar",
        "potcar_prefix":"./",
		"potcars":	{"Mg": "POTCAR_Mg"}
		
	},
	"properties": [
		{
            "type":         "eos",
			"vol_start":	0.9,
			"vol_end":	1.1,
			"vol_step":	0.01,
            "change_box":   true
		}
        ]
}

**DPGEN Version and Platform**
dpgen version: 0.10.3.dev1+g02037ad.d20211031
platform:centos7

**Job submission and computing cluster configuration**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by AnguseZhang** [comment]
What's the number of atom types in `confs/POSCAR` ? 
You can place `confs/POSCAR`

**Comment by xwchen2019** [comment]
only one type of atom in confs/POSCAR. Below is the POSCAR file
Mg
1.0
   3.0997561    0.0000000    0.0000000
  -1.0332520    2.9224780    0.0000000
  -1.0332520   -1.4612390    2.5309402
Mg
1
Direct
0.00000 0.00000 0.00000

**Comment by xwchen2019** [comment]
I check the results_task.json file (part of it is showing below), it seems that the atom_names is empty,
{
    "@module": "dpdata.system",
    "@class": "LabeledSystem",
    "data": {
        "atom_numbs": [
            1
        ],
        "atom_names": [],
        "atom_types": {
            "@module": "numpy",
            "@class": "array",
            "dtype": "int64",
            "data": [
                0
            ]
        },

**Comment by AnguseZhang** [comment]
I did not find `assert( len(data['atom_names'])==len(data['atom_numbs']) )` in the current `devel` branch. Could you please use the latest `devel` branch, and try again? If there is still problem, you can post the complete traceback.

**Comment by xwchen2019** [comment]
HI, Zhang, thanks for your reply. I re-install the dpgen, the dpgen version is  0.10.0 and try it again. i got the same error 

Traceback (most recent call last):
  File "/home/customer/.conda/envs/deepmd/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpgen/auto_test/run.py", line 57, in gen_test
    run_task(args.TASK, args.PARAM, args.MACHINE)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpgen/auto_test/run.py", line 48, in run_task
    post_property(confs, property_list)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpgen/auto_test/common_prop.py", line 259, in post_property
    prop.compute(os.path.join(path_to_work, 'result.json'), os.path.join(path_to_work, 'result.out'),
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpgen/auto_test/Property.py", line 108, in compute
    res, ptr = self._compute_lower(output_file, task_dirs, all_res)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpgen/auto_test/EOS.py", line 171, in _compute_lower
    task_result = loadfn(all_res[ii])
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/monty/serialization.py", line 89, in loadfn
    return json.load(fp, *args, **kwargs)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/monty/json.py", line 439, in decode
    return self.process_decoded(d)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/monty/json.py", line 408, in process_decoded
    return cls_.from_dict(data)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/monty/json.py", line 181, in from_dict
    return cls(**decoded)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpdata/system.py", line 1181, in __init__
    check_LabeledSystem(data)
  File "/home/customer/.conda/envs/deepmd/lib/python3.9/site-packages/dpdata/system.py", line 1859, in check_LabeledSystem
    assert( len(data['atom_names'])==len(data['atom_numbs']) )
AssertionError

**Comment by njzjz** [comment]
The issue should have been fixed by https://github.com/deepmodeling/dpdata/pull/151, or might be the same issue as https://github.com/deepmodeling/dpdata/issues/359. The error happens with dpdata, and there is no error with dpgen.
