### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Gauyer** [deepmodeling/dpgen#711]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 238, in handle_unexpected_submission_state
    job.handle_unexpected_job_state()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 596, in handle_unexpected_job_state
    self.handle_unexpected_job_state()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 596, in handle_unexpected_job_state
    self.handle_unexpected_job_state()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 589, in handle_unexpected_job_state
    raise RuntimeError(f"job:{self.job_hash} {self.job_id} failed {self.fail_count} times.job_detail:{self}")
RuntimeError: job:c6857851fe723fe0cdcd13760b71df960060c666 984156 failed 3 times.job_detail:{'c6857851fe723fe0cdcd13760b71df960060c666': {'job_task_list': [{'command': "/bin/sh -c '{ if [ ! -f model.ckpt.index ]; then dp  train input.json; else dp  train input.json --restart model.ckpt; fi }'&&dp  freeze", 'task_work_path': '002', 'forward_files': ['input.json'], 'backward_files': ['frozen_model.pb', 'lcurve.out', 'train.log', 'model.ckpt.meta', 'model.ckpt.index', 'model.ckpt.data-00000-of-00001', 'checkpoint'], 'outlog': 'train.log', 'errlog': 'train.log'}], 'resources': {'number_node': 1, 'cpu_per_node': 0, 'gpu_per_node': 1, 'queue_name': '', 'group_size': 1, 'custom_flags': [], 'strategy': {'if_cuda_multi_devices': False, 'ratio_unfinished': 0.0}, 'para_deg': 1, 'module_purge': False, 'module_unload_list': [], 'module_list': [], 'source_list': [' /home/ubuntu/PdSe2DPGEN/deepmd.sh'], 'envs': {}, 'wait_time': 0, 'kwargs': {}}, 'job_state': <JobStatus.terminated: 4>, 'job_id': 984156, 'fail_count': 3}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 3001, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 2966, in run_iter
    run_train  (ii, jdata, mdata)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 615, in run_train
    submission.run_submission()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 182, in run_submission
    self.handle_unexpected_submission_state()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 241, in handle_unexpected_submission_state
    raise RuntimeError(
RuntimeError: Meet errors will handle unexpected submission state.
Debug information: remote_root==/home/ubuntu/PdSe2DPGEN/91ace5cf6cb8ae772581d30b20148d0d7d2e9836.
Debug information: submission_hash==91ace5cf6cb8ae772581d30b20148d0d7d2e9836.
Please check the dirs and scripts in remote_rootThe job information mentioned above may help

The issue mentioned above isn't clear ,how do i  get solution? 
Thank you!

**Comment by 13yong** [comment]
In my view，you can check the error through  /home/ubuntu/.local/lib/python3.9/site-packages/dpdispatcher/submission.py.

**Comment by phyoung6xu** [comment]
I was also met this error yesterday, and the error message in model_devi.log is
 _ERROR on proc 0: Neighbor list overflow, boost neigh_modify one (src/npair_full_bin_atomonly.cpp:89)
Last command: run             ${NSTEPS} upto
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor_

**Comment by phyoung6xu** [comment]
I was also met this error yesterday, and the error message in model_devi.log is
_ERROR on proc 0: Neighbor list overflow, boost neigh_modify one (src/npair_full_bin_atomonly.cpp:89)
Last command: run ${NSTEPS} upto
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor_

Would you mind to share your experience to solve this error?

**Comment by Gauyer** [comment]
> I was also met this error yesterday, and the error message in model_devi.log is _ERROR on proc 0: Neighbor list overflow, boost neigh_modify one (src/npair_full_bin_atomonly.cpp:89) Last command: run ${NSTEPS} upto application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0 [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1 : system msg for write_line failure : Bad file descriptor_
> 
> Would you mind to share your experience to solve this error?

Sorry to hear that , the problem i encountered  when processing the fp stage , u may check the network to get the solution , it seems that it not the error from dpgen itself.
