### ISSUE TITLE
RuntimeError: Meet errors will handle unexpected submission state

### ISSUE THREAD

**Issue by FeiYang0106** [deepmodeling/dpgen#719]
Hi~, when i use this respectable package, DPGEN, to train a model for MgO, i meet an error in the exploration step, i try to find the answers in the community but it cannot be fixed, so i need your help. Thanks in advance.
Traceback (most recent call last):
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/lib/python3.9/site-packages/dpgen/main.py", line 175, in main
    args.func(args)
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/lib/python3.9/site-packages/dpgen/generator/run.py", line 2714, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/lib/python3.9/site-packages/dpgen/generator/run.py", line 2689, in run_iter
    run_model_devi (ii, jdata, mdata)
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/lib/python3.9/site-packages/dpgen/generator/run.py", line 1259, in run_model_devi
    submission.run_submission()
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/lib/python3.9/site-packages/dpdispatcher/submission.py", line 205, in run_submission
    self.handle_unexpected_submission_state()
  File "/apps/users/caep-lzg/package/anaconda/envs/deepmd/lib/python3.9/site-packages/dpdispatcher/submission.py", line 241, in handle_unexpected_submission_state
    raise RuntimeError(
RuntimeError: Meet errors will handle unexpected submission state.
Debug information: remote_root==/apps/users/caep-lzg/xufy/deepmd/MgO-1/work/3fb625a642d5a03eb4c68934b29cfcfc0c24a379.
Debug information: submission_hash==3fb625a642d5a03eb4c68934b29cfcfc0c24a379.
Please check the dirs and scripts in remote_rootThe job information mentioned above may help.

and when the model is trained, the lmp package is awakened to do MD, and the important information of model_devi.log is

ERROR on proc 0: Neighbor list overflow, boost neigh_modify one (src/npair_full_bin_atomonly.cpp:89)
Last command: run             ${NSTEPS} upto
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

dpgen version 0.10 .0   deepmd-kit version 2.1.1   lmp version 2.0.2

**Comment by fukang97** [comment]
Do you find approaches to this bug?

**Comment by FeiYang0106** [comment]
> 

Yes, it is not the question about the DPGEN, it comes out this error message due to the step of thermodynamic conditions I set in keyword `press` is too larger so that the exploration of the low-pressure region is not adequate, so the error message is about lammps.
