### ISSUE TITLE
0.10.6 CentOS 7, ImportError: libffi.so.7

### ISSUE THREAD

**Issue by dingzhaohan** [deepmodeling/dpgen#833]
I have installed dpgen-0.10.6 using release package on CentOS 7.6, then I run dpgen -h and get errors below.

Traceback (most recent call last):
  File "./dpgen", line 7, in <module>
    from dpgen.main import main
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpgen/main.py", line 9, in <module>
    from dpgen.generator.run import gen_run
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpgen/generator/run.py", line 46, in <module>
    from dpgen.generator.lib.run_calypso import gen_structures,analysis,run_calypso_model_devi
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpgen/generator/lib/run_calypso.py", line 24, in <module>
    from dpgen.dispatcher.Dispatcher import make_dispatcher, make_submission
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpgen/dispatcher/Dispatcher.py", line 5, in <module>
    from dpdispatcher import Task, Submission, Resources, Machine
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpdispatcher/__init__.py", line 40, in <module>
    from .submission import Submission
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpdispatcher/submission.py", line 9, in <module>
    from dpdispatcher.machine import Machine
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpdispatcher/machine.py", line 3, in <module>
    from dpdispatcher.ssh_context import SSHSession
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/dpdispatcher/ssh_context.py", line 5, in <module>
    import os, paramiko, tarfile, time
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/opt/dpgen-0.10.6/dpgen/lib/python3.8/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

**Comment by HuangJiameng** [comment]
you can try installing `libffi`

**Comment by HuangJiameng** [comment]
Please check `/opt/dpgen-0.10.6/dpgen/lib` on your server. If you have libffi.so.6 instead of libffi.so.7, use command `ln -s libffi.so.6 libffi.so.7` to create a symbolic link can temporarily solve this problem. see https://blog.csdn.net/duguwanglong/article/details/107662421

**Comment by njzjz** [comment]
It looks that this issue is not related to dpgen. See https://github.com/pyca/bcrypt/issues/274.
