### ISSUE TITLE
how to set fp for gaussian in param.json

### ISSUE THREAD

**Issue by Zhhaibing** [deepmodeling/dpgen#970]
Hi dper,
    when I run a dpgen task, i want to calculate dft with gaussian, setup of this part is as follow:

 {...
 "fp_style":"gaussian",
  "shuffle_poscar":"false",
  "fp_task_min":5,
  "fp_task_max":20,
  "use_clusters":false,
  "fp_params":{
    "keywords":"force b3lyp/genecp scf(Fermi,Vshift=300,Ndamp=30)" ,
    "multiplicity":1,
    "nproc":6,    
    "basis_set":"C H O  0\n6-31G*\n****\nSe Cd 0\nLANL2DZ\n****\nSe Cd 0\nLANL2DZ"
  } 
}

and the program will return an error:

Traceback (most recent call last):
  File "/home/ljgroup1/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/home/ljgroup1/.local/lib/python3.9/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/home/ljgroup1/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 3642, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/ljgroup1/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 3625, in run_iter
    make_fp (ii, jdata, mdata)
  File "/home/ljgroup1/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 2825, in make_fp
    make_fp_gaussian(iter_index, jdata)
  File "/home/ljgroup1/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 2659, in make_fp_gaussian
    _link_fp_vasp_pp(iter_index, jdata)
  File "/home/ljgroup1/.local/lib/python3.9/site-packages/dpgen/generator/run.py", line 2356, in _link_fp_vasp_pp
    fp_pp_path = jdata['fp_pp_path']
KeyError: 'fp_pp_path'

this means that i need assign pseudopotential files for gaussian, and but i have assigned my basis set and pseudopotential via writing "basis_set" by writing basis set and pseudopotential in string format in fp_params, by refer the code of gaussian.py, this part code in gaussian.py is as follow:

    if 'basis_set' in fp_params:
        # custom basis set
        buff.extend(['', fp_params['basis_set'], ''])
        #print(type(fp_params['basis_set']))
    for kw in itertools.islice(keywords, 1, None):
        buff.extend(['\n--link1--', *chkkeywords, nprockeywords,
                    '#{}'.format(kw), '', titlekeywords, '', chargekeywords, ''])
    return '\n'.join(buff)

when i check the code of "make_fp_gaussian part", i find at this end of this function, a function named "_link_fp_vasp_pp(iter_index, jdata)" is called, that means i need rewrite the pseudopotential and basis set used in gaussian to  a vasp readable pseudopotential file for gaussian calculation? I do not know how to deal with this problem. And i also find "_link_fp_vasp_pp(iter_index, jdata)"  also be called by other fp function from pwscf to cp2k.

**Comment by njzjz** [comment]
It's safely to remove `_link_fp_vasp_pp(iter_index, jdata)`.

**Comment by Zhhaibing** [comment]
thanks for your help
