### ISSUE TITLE
paramiko.ssh_exception.AuthenticationException: Authentication failed.

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpgen#998]
**When I updated dpgen from 10.0 to 10.6, I encountered an ssh error**

**dpgen: 10.0 to 10.6**

**ssh erro for dpgen10.0**

![image](https://user-images.githubusercontent.com/71744229/196033151-303b6a97-fda0-44ed-89e2-dc2c0efbc553.png)

![image](https://user-images.githubusercontent.com/71744229/196033183-8934e60c-348f-4771-898a-d1d8a02badd4.png)
I solved the problem by changing the look_for_keys in client.py for 10.0 version, however, It doesnt work for 10.6 version.

**ssh erro for dpgen10.6**

Traceback (most recent call last):
  File "/data/jccao/app/deepmd2_1_5/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpgen/main.py", line 185, in main
    args.func(args)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpgen/generator/run.py", line 3642, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpgen/generator/run.py", line 3607, in run_iter
    run_train  (ii, jdata, mdata)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpgen/generator/run.py", line 598, in run_train
    submission = make_submission(
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpgen/dispatcher/Dispatcher.py", line 359, in make_submission
    machine = Machine.load_from_dict(abs_mdata_machine)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/machine.py", line 129, in load_from_dict
    context = BaseContext.load_from_dict(machine_dict)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/base_context.py", line 35, in load_from_dict
    context = context_class.load_from_dict(context_dict)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/ssh_context.py", line 350, in load_from_dict
    ssh_context = cls(
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/ssh_context.py", line 323, in __init__
    self.ssh_session = SSHSession(**remote_profile)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/ssh_context.py", line 44, in __init__
    self._setup_ssh()
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/utils.py", line 162, in wrapper
    return func(*args, **kwargs)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/dpdispatcher/ssh_context.py", line 166, in _setup_ssh
    ts.auth_password(self.username, self.password)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/paramiko/transport.py", line 1564, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/data/jccao/app/deepmd2_1_5/lib/python3.10/site-packages/paramiko/auth_handler.py", line 245, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

**Details**

**Comment by AnguseZhang** [comment]
You can see https://github.com/deepmodeling/dpgen/issues/722.

**Comment by caojiachun** [comment]
I run my "train" work in remote cluster.
The version of deepkit is 2.1.5.

"train" :[
  {
    "command": "dp",
    "machine": {
    	 "batch_type": "slurm",
     	"context_type": "SSHContext",
     	"local_root" : "./",
     	"remote_root":"/data/home/scv7215/run/work",
     "remote_profile":{
  "hostname":"",
  "username":"",
  "password":"",
  "port": 22
    }
	},
    "resources": {
      "number_node": 1,
	"gpu_per_node":1,
	"cpu_per_node":10,
	"queue_name":"gpu",
     "local_root":"./",
     "source_list":["/data/home/scv7215/run/env.sh"],
     "group_size": 1,
	"custom_flags":["ulimit -s unlimited"],
     "time_limit": "23:0:0"
    }
  }],

**Comment by caojiachun** [comment]
> You can see #722.
sorry, the erro in #722  is different from mine.

**Comment by AnguseZhang** [comment]
> > You can see #722.
> > sorry, the erro in #722  is different from mine.

Actually I want to say `Do you have to use SSHContext? Maybe you can use LocalContext to transfer files.`

**Comment by caojiachun** [comment]
> > > You can see #722.
> > > sorry, the erro in #722  is different from mine.
> 
> Actually I want to say `Do you have to use SSHContext? Maybe you can use LocalContext to transfer files.`

**Comment by caojiachun** [comment]
> > > You can see #722.
> > > sorry, the erro in #722  is different from mine.
> 
> Actually I want to say `Do you have to use SSHContext? Maybe you can use LocalContext to transfer files.`

Ok, thank you for your answer.
